import { useSyncExternalStore } from "react";
import { backgroundOf, useBackgroundPrefs, type Background } from "../lib/chatBackground.js";
import { getActiveTheme, subscribeTheme } from "../theme/store.js";

/** Static, seamless pictures generated by `pnpm backgrounds`; no drawing runs in the chat. */
const FILES = import.meta.glob("../backgrounds/*.svg", {
  query: "?url",
  import: "default",
  eager: true,
}) as Record<string, string>;

/**
 * The picture behind a chat, under its messages: everyone's or the chat's own, or the one
 * named by `background` for a sample. Nothing at all for no picture, so a chat without one
 * is drawn exactly as before.
 */
export function ChatBackdrop({
  conversation,
  background,
  scale = 1,
  swatch = false,
}: {
  conversation?: string;
  background?: Background;
  scale?: number;
  swatch?: boolean;
}) {
  const prefs = useBackgroundPrefs();
  const theme = useSyncExternalStore(subscribeTheme, getActiveTheme);
  const picked = background ?? backgroundOf(prefs, conversation);
  if (picked === "none") return null;
  const url = FILES[`../backgrounds/${picked}-${theme.appearance}.svg`];
  // Swatches stay recognisable at zero intensity; the sample shows the actual setting.
  const size = Math.round(400 * scale * (swatch ? 1 : prefs.scale / 100));
  return (
    <div className="chat-backdrop" data-bg={picked} aria-hidden="true">
      <i
        className="bg-picture"
        style={{
          backgroundImage: `url("${url}")`,
          backgroundSize: `${size}px`,
          opacity: swatch ? 1 : prefs.strength / 100,
        }}
      />
    </div>
  );
}
