import { useSyncExternalStore } from "react";
import { drawTile, useTile } from "../lib/backdropTile.js";
import { backgroundOf, backgroundPrefs, useBackgroundPrefs, type Background } from "../lib/chatBackground.js";
import { getActiveTheme, subscribeTheme } from "../theme/store.js";

/** Static, seamless pictures generated by `pnpm backgrounds`, shown as bitmaps drawn from them (backdropTile). */
const FILES = import.meta.glob("../backgrounds/*.svg", {
  query: "?url",
  import: "default",
  eager: true,
}) as Record<string, string>;

/**
 * The picture behind a chat, under its messages: everyone's or the chat's own, or the one
 * named by `background` for a sample. Nothing at all for no picture, so a chat without one
 * is drawn exactly as before.
 */
export function ChatBackdrop({
  conversation,
  background,
  scale = 1,
  swatch = false,
}: {
  conversation?: string;
  background?: Background;
  scale?: number;
  swatch?: boolean;
}) {
  const prefs = useBackgroundPrefs();
  const theme = useSyncExternalStore(subscribeTheme, getActiveTheme);
  const picked = background ?? backgroundOf(prefs, conversation);
  const src = picked === "none" ? undefined : FILES[`../backgrounds/${picked}-${theme.appearance}.svg`];
  // Swatches stay recognisable at zero intensity; the sample shows the actual setting.
  const size = Math.round(400 * scale * (swatch ? 1 : prefs.scale / 100));
  const tile = useTile(src, size);
  if (picked === "none") return null;
  // Until its first bitmap is drawn, the chat has the theme's plain ground.
  return (
    <div className="chat-backdrop" data-bg={picked} aria-hidden="true">
      {tile !== undefined && (
        <i
          className="bg-picture"
          style={{
            backgroundImage: `url("${tile}")`,
            backgroundSize: `${size}px auto`,
            opacity: swatch ? 1 : prefs.strength / 100,
          }}
        />
      )}
    </div>
  );
}

/** Draws everyone's picture ahead of time, so the first chat opened shows it at once. */
export function warmBackdrop(): void {
  const prefs = backgroundPrefs();
  if (prefs.background === "none") return;
  const src = FILES[`../backgrounds/${prefs.background}-${getActiveTheme().appearance}.svg`];
  if (src !== undefined) void drawTile(src, Math.round((400 * prefs.scale) / 100));
}
